package com.example.jetbrainsaquareview;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;


public class MainPage {
    /***
     * MartinR: This class was generated by Aqua itself, when setting up the project anew. It was slightly modified during the review of the Aqua IDE.
     * This class stores the element locators according to the PageObjectModel-approach.
     */
    @FindBy(xpath = "//*[@data-test-marker='Developer Tools']")
    public WebElement seeDeveloperToolsButton;

    @FindBy(xpath = "//*[@data-test='suggestion-action']")
    public WebElement findYourToolsButton;

    @FindBy(xpath = "//div[@data-test='main-menu-item' and @data-test-marker = 'Developer Tools']")
    public WebElement toolsMenu;

    //@FindBy(css = "[data-test='site-header-search-action']")
    @FindBy(css = "button[data-test='site-header-search-action']")
    public WebElement searchButton;

    @FindBy(css = "div[id='blog-posts']")
    public WebElement divBlogPosts;


    public MainPage(WebDriver driver) {
        PageFactory.initElements(driver, this);
    }
}
